auth:
  token:
    expiryInSeconds: 3600
  cors:
    allowedOrigins: http://localhost:4200

#logging:
#  level:
#    root: DEBUG
#    org.springframework.web: DEBUG

upload:
  location: /home/anandmuley/Uploads

server:
  port: 8080
  servlet:
    context-path: /merobo/api

spring:
  data.mongodb:
    hostname: localhost
    port: 27017
    database: merobo

  # Configuring File Size

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
      enabled: true
